name: Release

# Create a simple release and save EXE in Github
on: 
  workflow_dispatch:
    inputs:
      notes:
        type: string
        description: Release Notes

jobs:
  version: # Get current version
    uses: starburst997/yearly-version/.github/workflows/version.yml@v1
    secrets: inherit

  version_increment: # Increment only if release is successful
    uses: starburst997/yearly-version/.github/workflows/version.yml@v1
    needs: [release]
    secrets: inherit
    with:
      increment: true

  build-windows:
    uses: ./.github/workflows/windows.yml
    needs: [version]
    secrets: inherit

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: [version, build-windows]
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}
      
      - name: Tag release
        run: |
          git tag v${{ needs.version.outputs.version }}
          git push origin --tags

      - name: Generate Changelog
        if: ${{ inputs.notes != '' }}
        run: echo "${{ inputs.notes }}" > RELEASE.txt
        
      - name: Generate Changelog (empty)
        if: ${{ inputs.notes == '' }}
        run: echo "No notes" > RELEASE.txt

      - name: Download Windows Artifact
        uses: actions/download-artifact@v4
        with:
          name: build-windows
          path: windows

      - name: Release
        uses: starburst997/action-gh-release@v2
        with:
          body_path: RELEASE.txt
          token: ${{ secrets.GH_PAT }}
          tag_name: v${{ needs.version.outputs.version }}
          files: |
            windows/CodeSignCpp-unsigned.exe
            windows/CodeSignCpp.exe

      - name: Cleanup to avoid storage limit
        if: always()
        uses: starburst997/delete-artifact@v5
        with:
          name: build-windows